Remove unnecessary line
pf-robotics/kachaka-api pull request #8
Opened 2023-08-14 16:36 UTC by 3110

When using `utils/set_authorized_keys_from_github.ipynb` to set up `authorized_keys`, there is no need to paste the public key into `public_keys`.

2023-08-14 21:32 UTC, youtalk-pfr submitted a review, later dismissed
ありがとうございます！

2023-08-14 23:10 UTC, watanabe-pfr submitted a review, later dismissed
ありがとうございます！

2023-08-14 23:24 UTC, hidai-pfr approved these changes

2023-08-14 23:28 UTC, nozaki-pfr requested changes

2023-08-14 23:28 UTC, nozaki-pfr commented on README.md
> -    * 画面中央のpublic_keysに公開鍵のテキストを貼り付けます。
ありがとうございます！
画像で十分かもしれませんが、揃えるために以下を書いておきたいです。
せっかくPRいただいているのでこちら変更いただけないでしょうか。
お時間なければこちらでやっておきます！

* 画面中央のuserにgithubのユーザ名を入力します。

2023-08-15 00:12 UTC, 3110 commented on README.md
> -    * 画面中央のpublic_keysに公開鍵のテキストを貼り付けます。
変更しました！

2023-08-15 00:38 UTC, 3110 reviewed
変更しました！

2023-08-15 00:39 UTC, youtalk-pfr approved these changes
LGTM

2023-08-15 00:46 UTC, nozaki-pfr approved these changes
ありがとうございます！

2023-08-15 01:09 UTC, merged